#* ***************************************************************

# Filename: Makefile

# Description: Makefile findGF.o fight.o

# Version: 1.0

# Created: 2018/05/28

# Revision: none

# Compiler: make

# Author: Lv Hongbin

# Company: Shanghai JiaoTong Univerity

# **************************************************************/

OBJS=findGF.o fight.o

# $@=main

main: ${OBJS}
	gcc -o $@ ${OBJS}
clean:
	rm -f main ${OBJS}
